---
# Non Pacemaker specific setup
- name: Enable chronyd
  systemd:
    name: chronyd
    state: started
    enabled: True
- name: Time zone
  timezone:
    name: '{{ timezone }}'
- name: Remove name from /etc/hosts so it does not resolve 127.0.0.1
  lineinfile:
    path: /etc/hosts
    regexp: '{{ ansible_hostname }}'
    state: absent
- name: Disable firewalld
  systemd:
      name: firewalld.service
      enabled: False
      state: stopped
# Pacemaker requisites
- name: Software packages
  yum:
    name:
      - pcs
      - pacemaker
      - fence-agents-sbd
      - lvm2-cluster
      - gfs2-utils
      - sbd
      - watchdog
- name: Enable pcsd
  systemd:
    name: pcsd.service
    enabled: True
    state: started
# Storage Based Death requisites
- name: Load softdog module
  modprobe:
    name: softdog
- name: Enable softdog module on boot
  lineinfile:
    path: /etc/modules-load.d/softdog.conf
    line: softdog
    create: True
- name: Enable module loading on boot
  systemd:
    name: systemd-modules-load.service
    enabled: True
- name: Configure watchdog
  lineinfile:
    path: /etc/watchdog.d/device.conf
    line: "watchdog-device = /dev/watchdog"
    create: True
- name: Enable watchdog-ping
  systemd:
    name: watchdog-ping.service
    enabled: True
    state: started
# Create cluster
- name: Check if authenticated
  stat:
    path: /var/lib/pcsd/tokens
  register: tokens
- name: Password for hacluster
  when: not tokens.stat.exists
  user:
    name: hacluster
    password: '{{ pacemaker.password | password_hash("sha512") }}'
    update_password: always
- name: Authenticate cluster
  run_once: True
  command:
    cmd: '/sbin/pcs cluster auth {{ ansible_play_hosts | join(" ") }} -u hacluster'
    stdin: '{{ pacemaker.password }}'
    creates: /var/lib/pcsd/tokens
- name: Create cluster
  run_once: True
  command:
    cmd: '/sbin/pcs cluster setup --enable --name "{{ pacemaker.name }}" {{ ansible_play_hosts | join(" ") }}'
    creates: /var/lib/pacemaker/cib/cib.xml
- name: Start cluster
  pacemaker_cluster:
    state: online
...