galaxy_info:
  author: Raúl Pedroche
  description: Simple CentOS 7 Pacemaker cluster setup

  license: BSD-3-Clause

  min_ansible_version: 2.9

  platforms:
  - name: CentOS
    versions:
    - 7
    - 8
  - name: Debian
    versions:
    - 9
    - 10
  - name: Ubuntu
    versions:
    - 18.04
    - 20.04

  galaxy_tags:
  - cluster
  - pacemaker

dependencies: []
  